Here are the SQL commands to create the `wedding_enquiry` and `wedding_active` tables in PostgreSQL, which is used by Supabase:

**`wedding_enquiry` table:**

```sql
CREATE TABLE public.wedding_enquiry (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  phone text NOT NULL,
  amount numeric,
  package text,
  custom_events jsonb,
  CONSTRAINT wedding_enquiry_pkey PRIMARY KEY (id)
);
```

**`wedding_active` table:**

```sql
CREATE TABLE public.wedding_active (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  phone text NOT NULL,
  amount_total numeric,
  advance_paid numeric,
  remaining_amount numeric,
  event_date date,
  status text,
  CONSTRAINT wedding_active_pkey PRIMARY KEY (id)
);
```

These commands will create the tables with the specified fields. You can execute these commands in the Supabase SQL editor to create the tables in your database.